/**
 * Industry knowledge-base starter templates.
 *
 * Why these exist: a brand-new store's knowledge base is empty, and an
 * empty knowledge base means the confidence gate escalates literally every
 * question to a human (see modules/knowledge/retrieval.ts). A merchant who
 * connects Telegram in five minutes and then watches the AI answer nothing
 * concludes the product does not work — the failure looks like the AI, but
 * it is really a cold-start data problem. These templates give a new store
 * a plausible first knowledge base in one click, which the merchant then
 * edits to match reality.
 *
 * Deliberately pure data — no Prisma import, no DB calls, no `storeId`.
 * The caller decides which store the rows land in and who `created_by` is,
 * which is what keeps this file safe to import from the seed, from an API
 * route, and from tests alike. Attaching content to a store is always an
 * explicit, audited act by a human; see the note in prisma/seed.ts.
 *
 * Content notes: the copy is Saudi-market Arabic, and the restaurant
 * template is kept consistent with docs/15-saudi-market-and-restaurant-vertical.md
 * — Friday/Saturday weekend (§1), prayer-time gaps (§1), payment via a
 * link issued by a licensed system rather than in-chat payment (§3.4),
 * invoices coming from the POS as the single source of truth and never
 * generated by Maysoor (§2.2), and reservations handled inside the same
 * conversation (§7).
 */

export type IndustryTemplateKey = "restaurant" | "real_estate" | "salon" | "retail" | "fresh_seafood";

export interface IndustryKnowledgeEntry {
  /** Customer-phrased question — also stored in chunk metadata so the review UI can show it. */
  question: string;
  /** The answer the AI is allowed to ground on. Placeholders in [brackets] are meant to be edited. */
  answer: string;
  /** Coarse topic tag, mirrored into `knowledge_chunks.metadata` for filtering/analytics. */
  topic: "delivery" | "booking" | "pricing" | "hours" | "cancellation" | "general";
}

export interface IndustryTemplate {
  key: IndustryTemplateKey;
  /** Arabic label shown in the "choose your industry" step of onboarding. */
  name: string;
  /** Goes into `knowledge_sources.title`. */
  sourceTitle: string;
  /**
   * Goes into `knowledge_sources.type`. "faq" is an existing allowed value
   * (prisma/schema.prisma KnowledgeSource.type) — a new type value would
   * need every consumer of that column to learn about it, and these really
   * are FAQs, so there is nothing to gain from inventing one.
   */
  sourceType: "faq";
  entries: IndustryKnowledgeEntry[];
}

// Every answer is written with an explicit [placeholder] wherever a real
// number would be a lie (prices, phone numbers, addresses). A template that
// shipped invented prices would be worse than an empty knowledge base: the
// AI would answer confidently and wrongly, which is the one failure mode
// the confidence gate cannot catch — it measures retrieval certainty, not
// whether the stored text is true.

const restaurant: IndustryTemplate = {
  key: "restaurant",
  name: "مطاعم وكافيهات",
  sourceTitle: "الأسئلة الشائعة — مطاعم وكافيهات",
  sourceType: "faq",
  entries: [
    {
      question: "كم يستغرق التوصيل؟",
      answer:
        "التوصيل داخل [المدينة] يستغرق من ٣٠ إلى ٤٥ دقيقة من لحظة تأكيد الطلب، وقد يزيد إلى ساعة في أوقات الذروة (بعد صلاة المغرب وفي إجازة نهاية الأسبوع الخميس والجمعة). نرسل لك تحديث حالة الطلب في نفس المحادثة أولًا بأول حتى وصول السائق.",
      topic: "delivery",
    },
    {
      question: "وش مناطق التوصيل عندكم وكم رسومه؟",
      answer:
        "نوصّل لأحياء [قائمة الأحياء] برسوم [قيمة] ريال، والطلبات فوق [قيمة] ريال توصيلها مجاني. إذا كان حيّك خارج نطاقنا نقدر نجهّز طلبك للاستلام من الفرع مباشرة.",
      topic: "delivery",
    },
    {
      question: "أبي أحجز طاولة، كيف؟",
      answer:
        "احجز من نفس هذه المحادثة — أرسل لنا: عدد الأشخاص، اليوم والوقت، والفرع المطلوب، ونؤكد لك الحجز فورًا إذا كانت الطاولة متاحة. الحجز يُثبَّت لمدة ١٥ دقيقة بعد الموعد، وبعدها قد نضطر لإعطاء الطاولة لعميل آخر. نرسل لك تذكيرًا قبل الموعد بساعتين.",
      topic: "booking",
    },
    {
      question: "متى تفتحون؟ وش ساعات العمل؟",
      answer:
        "نفتح يوميًا من [الساعة] صباحًا حتى [الساعة] منتصف الليل، مع إغلاق قصير عند أوقات الصلاة. إجازة نهاية الأسبوع (الجمعة والسبت) نفتح من [الساعة]. في رمضان تتغيّر الأوقات: نفتح من قبل المغرب حتى [الساعة] بعد منتصف الليل.",
      topic: "hours",
    },
    {
      question: "كم أسعار الأصناف؟ وهل فيه ضريبة؟",
      answer:
        "الأسعار المعروضة في القائمة شاملة ضريبة القيمة المضافة ١٥٪. تبدأ الوجبات الرئيسية من [قيمة] ريال والمشروبات من [قيمة] ريال. الفاتورة الرسمية تصدر من نظام نقاط البيع لدينا وترسل لك بعد إتمام الطلب.",
      topic: "pricing",
    },
    {
      question: "كيف أدفع؟",
      answer:
        "نستقبل مدى والبطاقات الائتمانية وSTC Pay والدفع النقدي عند الاستلام. للطلبات عبر المحادثة نرسل لك رابط دفع آمن تكمل عبره العملية، ولا نطلب أبدًا بيانات بطاقتك داخل المحادثة.",
      topic: "pricing",
    },
    {
      question: "أبي ألغي طلبي أو حجزي",
      answer:
        "إلغاء الحجز متاح مجانًا حتى [عدد] ساعات قبل الموعد — أرسل لنا رسالة هنا وسنلغيه فورًا. أما الطلب فيمكن إلغاؤه ما دام لم يدخل التحضير في المطبخ؛ بعد بدء التحضير لا يمكن إلغاؤه، وإذا وصلك الطلب خطأ أو ناقصًا نعوّضك بالكامل.",
      topic: "cancellation",
    },
    {
      question: "هل الصنف اللي أبيه متوفر؟",
      answer:
        "بعض الأصناف تنفد خلال اليوم حسب الكمية المحضّرة. أرسل لنا اسم الصنف ونؤكد لك توفره الآن قبل ما تكمل الطلب، وإذا كان غير متوفر نقترح عليك البديل الأقرب له.",
      topic: "general",
    },
    {
      question: "هل عندكم أصناف بدون [مكوّن]؟ وهل الأكل حلال؟",
      answer:
        "كل اللحوم لدينا ذبح حلال ومن موردين معتمدين. نوضّح مكوّنات كل صنف عند الطلب، وإذا عندك حساسية من مكوّن معيّن أخبرنا قبل الطلب لنتأكد من تجهيزه بطريقة مناسبة أو نرشّح لك بديلًا.",
      topic: "general",
    },
  ],
};

const realEstate: IndustryTemplate = {
  key: "real_estate",
  name: "عقارات",
  sourceTitle: "الأسئلة الشائعة — مكاتب ووساطة عقارية",
  sourceType: "faq",
  entries: [
    {
      question: "أبي أحجز موعد معاينة للعقار",
      answer:
        "أرسل لنا رقم العقار أو رابطه، واليوم والوقت المناسبين لك، ونرتّب لك المعاينة مع المسؤول عن العقار. المعاينات متاحة من [اليوم] إلى [اليوم] خلال ساعات العمل، ونؤكد لك الموعد برسالة هنا قبلها بيوم.",
      topic: "booking",
    },
    {
      question: "وش ساعات العمل عندكم؟",
      answer:
        "نستقبل استفساراتكم يوميًا من [الساعة] صباحًا حتى [الساعة] مساءً، والجمعة إجازة. الرسائل خارج ساعات العمل نرد عليها أول يوم عمل، والاستفسارات العاجلة يمكن تحويلها لموظف مباشرة من هذه المحادثة.",
      topic: "hours",
    },
    {
      question: "كم سعر الوحدة؟ وهل السعر قابل للتفاوض؟",
      answer:
        "أسعار الوحدات تختلف حسب المساحة والدور والموقع، وتبدأ من [قيمة] ريال. أرسل لنا رقم العقار ونزوّدك بالسعر الحالي والمساحة والمخطط. التفاوض على السعر يتم مع المالك عبرنا، وننقل لك الرد رسميًا.",
      topic: "pricing",
    },
    {
      question: "كم عمولة المكتب؟ وهل فيه رسوم إضافية؟",
      answer:
        "عمولة الوساطة [نسبة]٪ من قيمة الصفقة وتُدفع عند إتمام التعاقد، إضافة إلى رسوم توثيق العقد في منصة إيجار للإيجارات. لا توجد أي رسوم مقابل المعاينة أو الاستفسار.",
      topic: "pricing",
    },
    {
      question: "وش الأوراق المطلوبة للإيجار أو الشراء؟",
      answer:
        "للإيجار: صورة الهوية الوطنية أو الإقامة، وتوثيق العقد عبر منصة إيجار. للشراء: الهوية، وصك الملكية يُنقل عبر كتابة العدل، مع خطاب الجهة التمويلية إذا كان الشراء بتمويل بنكي. نساعدك في كامل الإجراءات خطوة بخطوة.",
      topic: "general",
    },
    {
      question: "متى يتم تسليم الوحدة؟",
      answer:
        "تسليم الوحدات الجاهزة يتم خلال [عدد] أيام من توقيع العقد وسداد الدفعة الأولى. الوحدات تحت الإنشاء موعد تسليمها [التاريخ] حسب الجدول المعتمد، ونحدّثك بأي تغيير رسميًا في هذه المحادثة.",
      topic: "delivery",
    },
    {
      question: "أبي ألغي الموعد أو أأجّله",
      answer:
        "إلغاء أو تأجيل موعد المعاينة متاح بدون أي رسوم — أخبرنا قبل الموعد بـ[عدد] ساعات على الأقل حتى نتيح الوقت لعميل آخر. أما إلغاء عقد موقّع فيخضع لشروط العقد نفسه ويحوّل لموظف مختص للمراجعة.",
      topic: "cancellation",
    },
    {
      question: "هل المكتب مرخّص؟",
      answer:
        "نعم، المكتب مرخّص من الهيئة العامة للعقار برقم [رقم الترخيص] وسجل تجاري ساري، وجميع تعاملاتنا موثّقة رسميًا. يسعدنا تزويدك بنسخة من الترخيص عند الطلب.",
      topic: "general",
    },
  ],
};

const salon: IndustryTemplate = {
  key: "salon",
  name: "صالونات ومراكز تجميل",
  sourceTitle: "الأسئلة الشائعة — صالونات ومراكز تجميل",
  sourceType: "faq",
  entries: [
    {
      question: "كيف أحجز موعد؟",
      answer:
        "احجزي من نفس المحادثة — أرسلي لنا الخدمة المطلوبة واليوم والوقت المفضّل، ونؤكد لك الموعد فورًا إذا كان متاحًا أو نقترح أقرب وقت بديل. نرسل لك تذكيرًا قبل الموعد بيوم.",
      topic: "booking",
    },
    {
      question: "وش أوقات العمل؟",
      answer:
        "نستقبلكم يوميًا من [الساعة] صباحًا حتى [الساعة] مساءً، مع إغلاق قصير عند أوقات الصلاة، والجمعة من [الساعة] فقط. في المواسم (الأعياد ورمضان) نمدد ساعات العمل ونعلن ذلك هنا.",
      topic: "hours",
    },
    {
      question: "كم أسعار الخدمات؟",
      answer:
        "تبدأ أسعار [الخدمة] من [قيمة] ريال، و[الخدمة] من [قيمة] ريال، وجميع الأسعار شاملة ضريبة القيمة المضافة ١٥٪. السعر النهائي قد يختلف حسب طول الشعر أو عدد الجلسات، ونوضّحه لك قبل بدء الخدمة.",
      topic: "pricing",
    },
    {
      question: "هل فيه عروض أو باقات؟",
      answer:
        "نعم، لدينا باقات شهرية وباقات للعرائس بخصم يصل إلى [نسبة]٪، وعروض موسمية نعلنها هنا. أخبرينا بالخدمات التي تهمك ونجهّز لك أنسب باقة.",
      topic: "pricing",
    },
    {
      question: "كم تستغرق الجلسة؟",
      answer:
        "مدة [الخدمة] تقريبًا [عدد] دقيقة، و[الخدمة] من [عدد] إلى [عدد] دقيقة. ننصحك بالحضور قبل الموعد بعشر دقائق حتى لا يتأثر وقت الجلسة، لأن التأخر أكثر من ١٥ دقيقة قد يستدعي إعادة الجدولة.",
      topic: "general",
    },
    {
      question: "هل تقدّمون خدمة منزلية؟",
      answer:
        "نعم، الخدمة المنزلية متاحة داخل [المدينة] برسوم انتقال [قيمة] ريال، وتحتاج حجزًا مسبقًا قبل [عدد] ساعة على الأقل. وقت وصول الفريق يتراوح بين [عدد] و[عدد] دقيقة حسب الحي وحركة المرور.",
      topic: "delivery",
    },
    {
      question: "أبي ألغي الموعد أو أغيّره",
      answer:
        "الإلغاء أو التغيير مجاني حتى [عدد] ساعات قبل الموعد — راسلينا هنا ونعدّله لك. الإلغاء بعد ذلك أو عدم الحضور قد يترتب عليه رسوم [قيمة] ريال أو خصم من قيمة الباقة، لأن الموعد يُحجز على حساب عميلات أخريات.",
      topic: "cancellation",
    },
    {
      question: "هل الصالون نسائي بالكامل؟ وهل الأدوات معقّمة؟",
      answer:
        "الصالون نسائي بالكامل وطاقم العمل نساء فقط، ولا يُسمح بالتصوير داخله حفاظًا على الخصوصية. جميع الأدوات تُعقَّم بعد كل استخدام، ونستخدم أدوات يمكن التخلص منها للخدمات التي تتطلب ذلك.",
      topic: "general",
    },
  ],
};


// Online retail — the largest segment on Salla and Zid, and the one a new
// merchant most often arrives from. The questions below are not invented:
// they are the ones a Saudi store gets before a customer will buy, in the
// order they get asked. Shipping and returns dominate, because that is what
// a first-time buyer is actually risking.
//
// Same placeholder rule as every other template: any real number is a
// [placeholder]. Shipping "3–5 days" written as fact for a store that takes
// 10 is worse than silence — the AI answers it confidently, and the
// confidence gate cannot catch it because that gate measures retrieval
// certainty, not whether the stored sentence is true.
const retail: IndustryTemplate = {
  key: "retail",
  name: "متاجر إلكترونية (تجزئة)",
  sourceTitle: "الأسئلة الشائعة — متجر إلكتروني",
  sourceType: "faq",
  entries: [
    {
      question: "متى يوصل طلبي؟",
      answer:
        "الطلبات داخل [المدينة] تصل خلال [٢-٣] أيام عمل، وبقية مناطق المملكة خلال [٣-٥] أيام عمل. تُشحن الطلبات المؤكدة قبل الساعة [٢] ظهرًا في نفس اليوم. يصلك رقم التتبّع على جوالك فور خروج الشحنة من المستودع.",
      topic: "delivery",
    },
    {
      question: "كم رسوم الشحن؟ وهل فيه شحن مجاني؟",
      answer:
        "رسوم الشحن [٢٥] ريالًا داخل المملكة، ومجاني للطلبات فوق [٢٠٠] ريال. تظهر الرسوم النهائية في صفحة الدفع قبل تأكيد الطلب، فلا توجد أي مبالغ تُضاف بعدها.",
      topic: "delivery",
    },
    {
      question: "أبغى أرجّع المنتج، وش الإجراءات؟",
      answer:
        "يمكنك إرجاع المنتج خلال [١٤] يومًا من الاستلام بشرط أن يكون بحالته الأصلية مع العلبة والملحقات وغير مستخدم. أرسل لنا رقم الطلب وصورة المنتج هنا، ونرتّب لك الاستلام من عنوانك. يُعاد المبلغ خلال [٥-٧] أيام عمل على نفس وسيلة الدفع.",
      topic: "cancellation",
    },
    {
      question: "المنتج وصلني تالف / غلط، وش أسوي؟",
      answer:
        "نعتذر عن ذلك. أرسل لنا رقم الطلب وصورة واضحة للمنتج كما وصلك، ونستبدله أو نعيد المبلغ كاملًا حسب رغبتك — والشحن علينا في الحالتين. لا تحتاج لإعادة تغليفه بشكل خاص، فقط احتفظ به كما هو حتى نتواصل معك.",
      topic: "cancellation",
    },
    {
      question: "أقدر ألغي الطلب أو أعدّله؟",
      answer:
        "نعم، ما دام الطلب لم يخرج من المستودع. أرسل لنا رقم الطلب فورًا وسنتحقق. إذا كان قد شُحن فعلًا، يمكنك رفضه عند الاستلام أو إرجاعه بعد الاستلام حسب سياسة الإرجاع.",
      topic: "cancellation",
    },
    {
      question: "هل المنتج متوفر بمقاس/لون ثاني؟",
      answer:
        "المتوفر حاليًا يظهر مباشرة في صفحة المنتج على المتجر — الخيارات المنفدة تظهر باهتة وغير قابلة للاختيار. أخبرنا باسم المنتج والمقاس أو اللون الذي تريده ونتحقق لك، وإذا كان منفدًا نبلغك فور توفّره.",
      topic: "general",
    },
    {
      question: "وش طرق الدفع المتاحة؟",
      answer:
        "نستقبل مدى، والبطاقات الائتمانية (فيزا وماستركارد)، وApple Pay، وتابي/تمارا للتقسيط. جميع المدفوعات تتم عبر بوابة آمنة، ولا نحتفظ ببيانات بطاقتك إطلاقًا.",
      topic: "pricing",
    },
    {
      question: "هل الأسعار شاملة الضريبة؟",
      answer:
        "نعم، جميع الأسعار المعروضة شاملة ضريبة القيمة المضافة [١٥٪]. الفاتورة الضريبية تصلك على بريدك الإلكتروني بعد إتمام الطلب، وتقدر تطلبها منّا في أي وقت برقم الطلب.",
      topic: "pricing",
    },
    {
      question: "عندكم كود خصم أو عروض؟",
      answer:
        "العروض الحالية معروضة في قسم [العروض] على المتجر. للحصول على أكواد الخصم أولًا بأول، اشترك في القائمة البريدية أو تابع حسابنا [@الحساب]. أكواد الخصم تُطبَّق في صفحة الدفع قبل تأكيد الطلب.",
      topic: "pricing",
    },
    {
      question: "متى تردّون على الرسائل؟",
      answer:
        "نردّ آليًا على مدار الساعة، وفريقنا البشري متاح من [٩ صباحًا] إلى [٩ مساءً] طوال أيام الأسبوع عدا [الجمعة]. لو كان سؤالك يحتاج موظفًا، نحوّلك له مباشرة وتصلك الإجابة في نفس المحادثة.",
      topic: "hours",
    },
    {
      question: "هل تشحنون خارج السعودية؟",
      answer:
        "[نشحن حاليًا داخل المملكة فقط / نشحن إلى دول الخليج خلال ٥-٧ أيام عمل برسوم تُحسب حسب الوزن والوجهة]. تواصل معنا بوجهتك ونعطيك التكلفة والمدة بالضبط قبل الطلب.",
      topic: "delivery",
    },
    {
      question: "وين طلبي؟ صار له كم يوم",
      answer:
        "أرسل لنا رقم الطلب ونتحقق من حالته فورًا. إذا تجاوز الطلب المدة المتوقعة، نتابع مع شركة الشحن نيابةً عنك ونرجع لك بتحديث — ولا نغلق المحادثة حتى يصلك.",
      topic: "delivery",
    },
  ],
};

// Fresh seafood / daily-catch food. This is NOT a variant of `retail`, and
// giving a fishmonger the retail template is an active mistake — the two
// disagree on the answers that matter most:
//
//   retail says "return within 14 days, unused, in its original box"
//   fresh food says "tell us within HOURS, and we cannot resell it either way"
//
//   retail says "3–5 business days, tracking number from the courier"
//   fresh food says "same day / next day, our own refrigerated car, and you
//   must be home to receive it"
//
// A perishable-goods store answering with retail's numbers would be
// promising a two-week return window on fish. So the questions below are the
// ones a seafood buyer actually asks before their first order, and the ones
// that generate the most support load afterwards.
//
// The biggest of those is WEIGHT. Fish is priced per kilo *before* cleaning,
// gutting removes a large fraction of it, and shrimp loses roughly half once
// the head and shell are off. A customer who ordered "1 kg" and unpacks 550 g
// of shrimp meat believes they were shorted — this is the single most common
// dispute in the trade, and answering it up front prevents it. Two separate
// entries cover it, because customers ask it twice: once before buying
// ("how much do I order?") and once after ("why is this light?").
//
// Same placeholder rule as everywhere else: every real number is a
// [placeholder]. The delivery window and the return window especially — a
// wrong return window on perishable food is not a rounding error, it is the
// store either eating losses it never agreed to or refusing a claim the
// customer was told they had.
const freshSeafood: IndustryTemplate = {
  key: "fresh_seafood",
  name: "بحريات وأغذية طازجة",
  sourceTitle: "الأسئلة الشائعة — أسماك وبحريات طازجة",
  sourceType: "faq",
  entries: [
    {
      question: "متى يوصل طلبي؟",
      answer:
        "نوصّل داخل [المدينة] خلال [٢٤] ساعة من تأكيد الطلب. البحريات تُجهَّز خصيصًا بعد الطلب — تُنظَّف وتُغلَّف لك أنت، ثم تُنقل في سيارات مبرّدة، فلا نشحنها مع شركات الشحن العادية. نتواصل معك قبل الوصول لتنسيق وقت الاستلام.",
      topic: "delivery",
    },
    {
      question: "وش المناطق اللي توصلون لها؟ وكم رسوم التوصيل؟",
      answer:
        "نغطي [المدن/الأحياء] برسوم [قيمة] ريال، والطلبات فوق [قيمة] ريال توصيلها مجاني. خارج هذا النطاق لا نضمن سلسلة التبريد، ولذلك لا نوصّل له — الطزاجة عندنا شرط لا خدمة إضافية.",
      topic: "delivery",
    },
    {
      question: "الوزن المكتوب قبل التنظيف ولا بعده؟",
      answer:
        "الوزن المعروض في المتجر هو الوزن **قبل التنظيف**، وهذا هو المتعارف عليه في بيع البحريات. بعد إزالة الأحشاء والقشور ينقص الوزن، ومقدار النقص يختلف حسب النوع. أما الروبيان فيفقد قرابة نصف وزنه بعد نزع الرأس والقشر والذيل — يعني الكيلو يصير تقريبًا [نصف] كيلو لحم صافي. إذا تبي كيلو لحم صافي، اطلب [ضعف] الكمية أو اطلبه كاملًا بدون تنظيف.",
      topic: "pricing",
    },
    {
      question: "استلمت الطلب ووزنه أقل من اللي طلبته",
      answer:
        "الفرق غالبًا سببه التنظيف لا نقص الكمية: نزن قبل التنظيف، وإزالة الأحشاء والرأس والقشر تنقص الوزن فعليًا. أرسل لنا رقم الطلب وصورة للميزان ونراجع الطلب من عندنا فورًا — وإذا طلع الفرق من عندنا نعوّضك عنه كاملًا بدون نقاش.",
      topic: "general",
    },
    {
      question: "أقدر أطلبه منظّف ومقطّع؟",
      answer:
        "نعم، تختار طريقة التنظيف والتقطيع اللي تناسبك عند الطلب: [كامل / منظّف / شرائح / مكعبات]، والروبيان [مقشّر بالكامل / مع الذيل / كامل]. التجهيز يتم في بيئة صحية معقّمة بعد استلام طلبك مباشرة. إذا تبيه بدون تنظيف، أخبرنا **قبل** بدء التجهيز لأنه لا يمكن التراجع بعده.",
      topic: "general",
    },
    {
      question: "كيف تضمنون وصوله طازج؟",
      answer:
        "الطلب يُجهَّز من صيد اليوم بعد طلبك مباشرة، ثم يُغلَّف بإحكام ويوضع في صناديق حافظة للبرودة مغطاة بالثلج، وينتقل في سيارات مبرّدة حتى باب بيتك. علامات الطزاجة اللي تقدر تتأكد منها بنفسك عند الاستلام: عيون صافية لامعة غير غائرة، جسم متماسك يرتد عند الضغط عليه، ورائحة بحر منعشة.",
      topic: "general",
    },
    {
      question: "إذا وصلني الطلب مو طازج، وش أسوي؟",
      answer:
        "تواصل معنا خلال [ساعتين] كحد أقصى من وقت الاستلام مع رقم الطلب وصورة واضحة للمنتج، ونستبدله أو نعيد لك المبلغ. المدة قصيرة لأن البحريات منتج حسّاس جدًا ولا يمكن الحكم على حالته بعد ساعات من الاستلام — وهذا الشرط لحمايتك ولحمايتنا معًا. اتصل أو راسلنا على [رقم خدمة العملاء].",
      topic: "cancellation",
    },
    {
      question: "أقدر أرجّع الطلب لأني غيّرت رأيي؟",
      answer:
        "المنتجات الطازجة تُجهَّز خصيصًا لطلبك وتُنظَّف وتُغلَّف باسمك، ولذلك لا يمكن إرجاعها لمجرد تغيير الرأي — نظام التجارة الإلكترونية السعودي يستثني السلع القابلة للتلف من حق العدول. لكن إذا لم يكن الطلب مطابقًا لمعايير الطزاجة، فحقك محفوظ بالكامل. أما إلغاء الطلب قبل بدء التجهيز فمتاح فورًا؛ راسلنا برقم الطلب.",
      topic: "cancellation",
    },
    {
      question: "هل النوع اللي أبيه متوفر اليوم؟",
      answer:
        "التوفر يعتمد على صيد اليوم ويتغيّر يوميًا — الأنواع الموسمية قد تنقطع لأيام. أرسل لنا اسم النوع والكمية ونؤكد لك توفره الآن قبل ما تكمل الطلب، وإذا كان غير متوفر نرشّح لك أقرب بديل بنفس طريقة الطبخ.",
      topic: "general",
    },
    {
      question: "لازم أكون موجود وقت التوصيل؟",
      answer:
        "نعم — الطلب مبرّد ولا يمكن تركه على الباب. يلتزم العميل بالتواجد في وقت التوصيل المحدد أو تفويض شخص يستلم نيابةً عنه. إذا تعذّر عليك الاستلام أخبرنا مبكرًا ونعيد جدولة التوصيل، لأن رجوع الطلب في السيارة يعني خسارته.",
      topic: "delivery",
    },
    {
      question: "وش طرق الدفع؟ وهل الأسعار شاملة الضريبة؟",
      answer:
        "نستقبل [مدى، البطاقات الائتمانية، Apple Pay، الدفع عند الاستلام]، وجميع المدفوعات تتم عبر بوابة آمنة ولا نطلب بيانات بطاقتك في المحادثة أبدًا. الأسعار المعروضة [شاملة] ضريبة القيمة المضافة، وتصلك الفاتورة بعد إتمام الطلب.",
      topic: "pricing",
    },
    {
      question: "كيف أحفظه في البيت؟ وكم يبقى صالح؟",
      answer:
        "استخدمه في نفس اليوم إن أمكن. للحفظ القصير: ضعه في أبرد جزء من الثلاجة على ثلج ويُستهلك خلال [٢٤] ساعة. للحفظ الأطول: جمّده فورًا بعد الاستلام في أكياس محكمة، ويفضّل تقسيمه لوجبات قبل التجميد لأن إعادة تجميد ما ذاب تفسده. الإذابة تكون في الثلاجة لا في ماء ساخن.",
      topic: "general",
    },
    {
      question: "متى تردّون على الرسائل؟",
      answer:
        "نردّ آليًا على مدار الساعة، وفريقنا متاح من [الساعة] إلى [الساعة] يوميًا. الطلبات المستعجلة وطلبات المناسبات الكبيرة نفضّل التنسيق لها مبكرًا لأن الكميات تعتمد على صيد اليوم.",
      topic: "hours",
    },
  ],
};

export const INDUSTRY_TEMPLATES: Record<IndustryTemplateKey, IndustryTemplate> = {
  retail,
  fresh_seafood: freshSeafood,
  restaurant,
  real_estate: realEstate,
  salon,
};

export function listIndustryTemplates(): IndustryTemplate[] {
  return Object.values(INDUSTRY_TEMPLATES);
}

/**
 * Looks a template up by key, for a key that arrives from a URL.
 *
 * The `hasOwn` guard is NOT defensive padding. `INDUSTRY_TEMPLATES` is an
 * ordinary object literal, so a plain index lookup walks the prototype chain:
 * `INDUSTRY_TEMPLATES["__proto__"]` returns an object and
 * `INDUSTRY_TEMPLATES["constructor"]` returns a function — both TRUTHY. The
 * apply route reads `template.entries.map(...)` right after its `if
 * (!template) 404`, so those keys sailed past the 404 and crashed on an
 * undefined `.entries` — a 500 that reads like an outage, from a URL any
 * authenticated manager can type.
 */
export function getIndustryTemplate(key: string): IndustryTemplate | undefined {
  if (!Object.hasOwn(INDUSTRY_TEMPLATES, key)) return undefined;
  return INDUSTRY_TEMPLATES[key as IndustryTemplateKey];
}

/**
 * One chunk = one Q&A pair, in the same "س: ... ج: ..." shape the learning
 * loop already writes into ai_suggested_knowledge (channels/routes.ts), so
 * retrieval scores template content and merchant-approved content
 * identically — the retriever tokenizes the question text along with the
 * answer, which is what lets a customer's phrasing match at all.
 */
export function templateChunkContent(entry: IndustryKnowledgeEntry): string {
  return `س: ${entry.question}\nج: ${entry.answer}`;
}

/** Body for `knowledge_sources.raw_text` — the whole template as one document. */
export function templateRawText(template: IndustryTemplate): string {
  return template.entries.map(templateChunkContent).join("\n\n");
}

/**
 * Metadata for `knowledge_chunks.metadata`. Tagging the origin is what
 * later makes it possible to tell "the merchant wrote this" from "we
 * seeded this and nobody ever edited it" — e.g. to stop nagging a store
 * whose knowledge base is technically non-empty but entirely placeholders.
 */
export function templateChunkMetadata(
  template: IndustryTemplate,
  entry: IndustryKnowledgeEntry
): { origin: "industry_template"; industry: IndustryTemplateKey; topic: string; question: string } {
  return {
    origin: "industry_template",
    industry: template.key,
    topic: entry.topic,
    question: entry.question,
  };
}
